[versions]
telegrambots = '10.0.0'
springBoot = '4.1.0'
springDependencyManagement = '1.1.7'
gradleGitProperties = '4.0.1'
sonarqube = '7.4.0.8496'

[libraries]
telegrambots-springboot-longpolling-starter = { module = "org.telegram:telegrambots-springboot-longpolling-starter", version.ref = "telegrambots" }
telegrambots-client = { module = "org.telegram:telegrambots-client", version.ref = "telegrambots" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
gradle-git-properties = { id = "com.gorylenko.gradle-git-properties", version.ref = "gradleGitProperties" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }